### ISSUE TITLE
Master - Issue List

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/Awakens-Latest#14]
**Missing Commands**
- [ ] /logout (Do I need to explain this?)
- [ ] /safe (Would turn off BG, Images and Audio)
- [ ] /forgotpw (I feel this is self explanatory as well, use to have a dialog box with questions)
- [ ] /blocktor (User to block all access to using Tor. Was Toggleable.)
- [ ] /blockproxy (Would block all unsafe proxy access, Was toggleable.)
- [ ] /removehat (Going into the database constantly, sux.)
- [ ] /toggle bg (/toggle background works, but it'd be nice if both were functional.)
- [ ] /hatlist user(listed all hats you had access to or specified user, specifying a user would be admins only)
- [ ] /vpm user(Use to be able to bring up Visual PM with user)
- [x] /banip (Use to be able to permanent ban IPs)
- [x] /ban (Not sure how current one functions. use to be able to permanently ban a nick.)
- [ ] Image Hover Zoom (Holding CTRL+Hovering over image would expand it. Image would stay on screen until CTRL was released.)
- [x] ~~/help (Bring up Help HTML Page in iFrame)~~

**Missing Features:**
- [ ] Status Color next to names:
(https://github.com/FroggMaster/Awakens-Latest/issues/4 and https://github.com/FroggMaster/Awakens-Latest/issues/6)
Green was Active
Yellow was Inactive for <30 Mins
Red was Inactive for >30 mins
Additions:
Blue can be user is typing
Orange to indicate use has gotten PM

- [ ]  Topic Name + Dates (https://github.com/FroggMaster/Awakens-Latest/issues/2)

Pertinent Bugs

- [ ] Text Bar/Input Spacing https://github.com/FroggMaster/Awakens-Latest/issues/15
- [ ] /AFK MSG (https://github.com/FroggMaster/Awakens-Latest/issues/13) + Related (https://github.com/FroggMaster/Awakens-Latest/issues/4)
- [ ] Left Click User Menu Doesn't Close (https://github.com/FroggMaster/Awakens-Latest/issues/11)
- [ ] PM Windows Don't Minimize (https://github.com/FroggMaster/Awakens-Latest/issues/10)
- [ ] PM Notifcation/Sounds (https://github.com/FroggMaster/Awakens-Latest/issues/6)

**Comment by DayDun** [comment]
how would we detect proxies?

**Comment by DayDun** [comment]
And for pass recovery, the safest way would be if you assigned an email to you account

**Comment by FroggMaster** [comment]
For password recovery previously, we had people Pick from a list/Set a Secret Question + Answer
Detect Proxies we had an API, I'll have to do some digging to figure out the one we had in the previous code.
